### ISSUE TITLE
mobile - fix card scrolling

### ISSUE THREAD

**Issue by peterhershey** [ianbusko/the-noted-project#27] opened 2018-09-06 15:03 UTC
scrolling down on a card is fine (a little slow, but it works), but when you scroll back up it first scrolls through the article beneath the card, then only scrolls the card when the article is done scrolling

**Comment by ianbusko** [comment] 2018-09-07 15:07
@peterhershey can you verify that this is still happening? I can't reproduce it.

**Comment by peterhershey** [comment] 2018-09-07 16:26
It no longer appears to be happening

**Comment by ianbusko** [comment] 2018-09-07 16:35
Can you close the issue?

**Comment by peterhershey** [comment] 2018-09-07 17:19
Yes when I’m at my computer

**Closed** 2018-09-07 19:47 UTC
Labels: bug
